ERROR - 2025-03-17 04:13:57 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP\htdocs\lab11_upb\ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP\htdocs\lab11_upb\ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\XAMPP\htdocs\lab11_upb\ci4\app\Controllers\Artikel.php(10): CodeIgniter\BaseModel->findAll()
#7 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(933): App\Controllers\Artikel->index()
#8 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Artikel))
#9 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\XAMPP\htdocs\lab11_upb\ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\XAMPP\htdocs\lab11_upb\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\XAMPP\htdocs\lab11_upb\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\XAMPP\htdocs\lab11_upb\ci4\system\rewrite.php(44): require_once('D:\\XAMPP\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP\htdocs\lab11_upb\ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP\htdocs\lab11_upb\ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\XAMPP\htdocs\lab11_upb\ci4\app\Controllers\Artikel.php(10): CodeIgniter\BaseModel->findAll()
#6 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(933): App\Controllers\Artikel->index()
#7 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Artikel))
#8 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP\htdocs\lab11_upb\ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 D:\XAMPP\htdocs\lab11_upb\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\XAMPP\htdocs\lab11_upb\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\XAMPP\htdocs\lab11_upb\ci4\system\rewrite.php(44): require_once('D:\\XAMPP\\htdocs...')
#13 {main}
CRITICAL - 2025-03-17 04:13:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: artikel]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `artikel`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Artikel.php(10): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Artikel->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Artikel))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\XAMPP\\htdocs\\lab11_upb\\ci4\\public\\index.php')
ERROR - 2025-03-17 04:23:56 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP\htdocs\lab11_upb\ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP\htdocs\lab11_upb\ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\XAMPP\htdocs\lab11_upb\ci4\app\Controllers\Artikel.php(10): CodeIgniter\BaseModel->findAll()
#7 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(933): App\Controllers\Artikel->index()
#8 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Artikel))
#9 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\XAMPP\htdocs\lab11_upb\ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\XAMPP\htdocs\lab11_upb\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\XAMPP\htdocs\lab11_upb\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\XAMPP\htdocs\lab11_upb\ci4\system\rewrite.php(44): require_once('D:\\XAMPP\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP\htdocs\lab11_upb\ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP\htdocs\lab11_upb\ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\XAMPP\htdocs\lab11_upb\ci4\app\Controllers\Artikel.php(10): CodeIgniter\BaseModel->findAll()
#6 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(933): App\Controllers\Artikel->index()
#7 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Artikel))
#8 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP\htdocs\lab11_upb\ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 D:\XAMPP\htdocs\lab11_upb\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\XAMPP\htdocs\lab11_upb\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\XAMPP\htdocs\lab11_upb\ci4\system\rewrite.php(44): require_once('D:\\XAMPP\\htdocs...')
#13 {main}
CRITICAL - 2025-03-17 04:23:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: artikel]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `artikel`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Artikel.php(10): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Artikel->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Artikel))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\XAMPP\\htdocs\\lab11_upb\\ci4\\public\\index.php')
ERROR - 2025-03-17 04:23:59 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP\htdocs\lab11_upb\ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP\htdocs\lab11_upb\ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\XAMPP\htdocs\lab11_upb\ci4\app\Controllers\Artikel.php(10): CodeIgniter\BaseModel->findAll()
#7 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(933): App\Controllers\Artikel->index()
#8 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Artikel))
#9 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\XAMPP\htdocs\lab11_upb\ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\XAMPP\htdocs\lab11_upb\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\XAMPP\htdocs\lab11_upb\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\XAMPP\htdocs\lab11_upb\ci4\system\rewrite.php(44): require_once('D:\\XAMPP\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP\htdocs\lab11_upb\ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP\htdocs\lab11_upb\ci4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP\htdocs\lab11_upb\ci4\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\XAMPP\htdocs\lab11_upb\ci4\app\Controllers\Artikel.php(10): CodeIgniter\BaseModel->findAll()
#6 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(933): App\Controllers\Artikel->index()
#7 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Artikel))
#8 D:\XAMPP\htdocs\lab11_upb\ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\XAMPP\htdocs\lab11_upb\ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 D:\XAMPP\htdocs\lab11_upb\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\XAMPP\htdocs\lab11_upb\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\XAMPP\htdocs\lab11_upb\ci4\system\rewrite.php(44): require_once('D:\\XAMPP\\htdocs...')
#13 {main}
CRITICAL - 2025-03-17 04:23:59 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: artikel]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `artikel`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Artikel.php(10): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Artikel->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Artikel))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\XAMPP\\htdocs\\lab11_upb\\ci4\\public\\index.php')
CRITICAL - 2025-03-17 04:36:18 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "template/admin_header.php"
[Method: GET, Route: admin/artikel]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('template/admin_header.php')
 2 SYSTEMPATH\View\View.php(475): CodeIgniter\View\View->render('template/admin_header', null, true)
 3 APPPATH\Views\artikel\admin_index.php(1): CodeIgniter\View\View->include('template/admin_header')
 4 SYSTEMPATH\View\View.php(224): include('D:\\XAMPP\\htdocs\\lab11_upb\\ci4\\app\\Views\\artikel\\admin_index.php')
 5 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('artikel/admin_index', [], true)
 7 APPPATH\Controllers\Artikel.php(18): view('artikel/admin_index', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Artikel->admin_index()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Artikel))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\XAMPP\\htdocs\\lab11_upb\\ci4\\public\\index.php')
